### ISSUE TITLE
TODO list 

### ISSUE THREAD

**Issue by yezhengmao1** [TUDB-Labs/mLoRA#258]
- [ ] auto hyperparameters search
- [ ] more rlhf methods support
- [ ] more model support
- [ ] the multimodal support
- [ ] auto-parallelizing
- [ ] better dispatcher and monitor

**Comment by mikecovlee** [comment]
I will migrate improvement from MoE-PEFT to m-LoRA step by step :)

**Comment by merlintang** [comment]
great

**Comment by shraddhaamohan** [comment]
Hey, first of all, this is great work! I'd love to see stable diffusion supported as well, infact I'd be happy to contribute this part. However it is my first time working on an opensource project, so would appreciate if you have some pointers on where I can get started!

**Comment by yezhengmao1** [comment]
> Hey, first of all, this is great work! I'd love to see stable diffusion supported as well, infact I'd be happy to contribute this part. However it is my first time working on an opensource project, so would appreciate if you have some pointers on where I can get started!

I'm not familiar with the stable diffusion, but you can refer to the BatchLoRA operator : https://github.com/TUDB-Labs/mLoRA/blob/main/mlora/model/modules/lora.py

and also refer to how the lora module works with the backbone model.

integrate the stable diffusion with our framework is a great idea, maybe it's not
